### ISSUE TITLE
css or charter triangle

### ISSUE THREAD

**Issue by openHacking** [openHacking/xhack#72]
1. css
```css
::after{
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: .255em;
  vertical-align: .255em;
  content: "";
  border-top: .3em solid;
  border-right: .3em solid transparent;
  border-bottom: 0;
  border-left: .3em solid transparent;
}
```

2. charter ⏷ ⏶
